/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  //tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  defiSidebar: [
    { type: 'doc', id: 'Tokenomics', label: 'Tokenomics', },
    { type: 'doc', id: 'DeFi-Metrics', label: 'DeFi Metrics', },
    {
      type: 'category', label: 'DeFi Primitives', items: [
        { type: 'doc', id: 'DEX', label: '🦄 DEX', },
        { type: 'doc', id: 'Stablecoins', label: '💲 Stablecoins', },
        { type: 'doc', id: 'Lending', label: '💰 Lending', },
        //{ type: 'doc', id: '', label: '💸 Fees and Staking', },
        { type: 'doc', id: 'Options', label: '📑 Options', },
        { type: 'doc', id: 'Futures', label: '➡️ Futures', },
        { type: 'doc', id: 'Other-Derivatives', label: '💎 Other Derivatives', },
        { type: 'doc', id: 'Liquid-Staking', label: '🌊 Liquid Staking', },
        { type: 'doc', id: 'Wrapped', label: '🍬 Wrapped', },
        { type: 'doc', id: 'Floaters', label: '🎈 Floaters', },
        { type: 'doc', id: 'Bridges', label: '🌉 Bridges', },
        { type: 'doc', id: 'Oracles', label: '🔮 Oracles', },
        { type: 'doc', id: 'Insurance', label: '🛡️ Insurance', },
        { type: 'doc', id: 'Mixing', label: '🌪️ Mixing', },
        { type: 'doc', id: 'Uncollateralized-Loans', label: '🍀 Uncollateralized Loans', },
        { type: 'doc', id: 'Synthetics', label: '🛢️ Synthetics', },
        { type: 'doc', id: 'RWA', label: '🏠 RWA', },
        { type: 'doc', id: 'Asset-Management', label: '🙌 Asset Management', },
        { type: 'doc', id: 'Money-Streaming', label: '🚿 Money Streaming', },
      ]
    },
    {
      type: 'category', label: 'DeFi Mechanics', items: [
        { type: 'doc', id: 'Incentives', label: '✨ Incentives', },
        { type: 'doc', id: 'Protocol-Owned-Liquidity', label: '🏛️ Protocol Owned Liquidity', },
        { type: 'doc', id: 'Vote-Escrow', label: '⏳ Vote Escrow (ve-)', },
        { type: 'doc', id: 'Real-Yield', label: '🗿 Real Yield', },
        { type: 'doc', id: 'Bribes', label: '🤑 Bribes', },
        { type: 'doc', id: 'Auctions', label: '🔨 Auctions', },
        { type: 'doc', id: 'Whitelists-Airdrops', label: '🪂 Whitelists, Airdrops', },
        { type: 'doc', id: 'Token-gated-Access', label: '🗝️ Token-gated Access', },
      ]
    },
    {
      type: 'category', label: 'NFTfi', items: [
        { type: 'doc', id: 'NFT-Marketplace', label: '🧩 NFT Marketplace', },
        { type: 'doc', id: 'NFT-Lend-and-Rent', label: '🧸 NFT Lend and Rent', },
        { type: 'doc', id: 'NFT-Case-Studies', label: '🖼 NFT Case Studies', },
        { type: 'doc', id: 'NFT-Analytics', label: '🐵 NFT Analytics', },
      ]
    },
    {
      type: 'category', label: 'GameFi', items: [
        { type: 'doc', id: 'Gaming', label: '🕹️ Gaming', },
        { type: 'doc', id: 'Gambling-Prediction-Markets', label: '🎰 Gambling, Prediction Markets', },
      ]
    },
    {
      type: 'category', label: 'Trading', items: [
        { type: 'doc', id: 'CEX', label: '💳 CEX', },
        { type: 'doc', id: 'Economics', label: '💱 Economics', },
        { type: 'doc', id: 'Fundamentals-DYOR', label: '📊 Fundamentals, DYOR', },
        { type: 'doc', id: 'Technicals-Charts', label: '📈 Technicals, Charts', },
        { type: 'doc', id: 'Farming', label: '🌾 Farming', },
      ]
    },
  ],
  web3Sidebar: [
    { type: 'doc', id: 'Options', label: 'Getting started', },
  ],
};

module.exports = sidebars;
